In [34]:
# Import Dependencies
import pandas as pd

In [35]:
# Create a path to the csv and read it into a Pandas DataFrame
csv_path = "Resources/ted_talks.csv"
df = pd.read_csv(csv_path)

df.head()

,comments,description,duration,event,languages,main_speaker,name,title,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,Do schools kill creativity?,47227110
1,265,With the same humor and humanity he exuded in ...,977,TED2006,43,Al Gore,Al Gore: Averting the climate crisis,Averting the climate crisis,3200520
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,26,David Pogue,David Pogue: Simplicity sells,Simplicity sells,1636292
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,35,Majora Carter,Majora Carter: Greening the ghetto,Greening the ghetto,1697550
4,593,You've never seen data presented like this. Wi...,1190,TED2006,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,The best stats you've ever seen,12005869

In [31]:
# Create bins in which to place values based upon TED Talk views
bins = [0, 199999, 399999, 599999, 799999, 999999, 1999999, 2999999, 3999999, 4999999, 50000000]

# Create labels for these bins

group_names = ["Sucks" , "Kinda sucks" , "sucks less" , "not bad" , "kinda okay",
               "okay" , "kinda good" , "pretty good" , "great" , "amazing"]

In [32]:
print(len(bins), len(group_names))

11 10

In [36]:
# Slice the data and place it into bins
df["ted_talks"] = pd.cut(df["views"], bins, labels=group_names, include_lowest=True)
df

,comments,description,duration,event,languages,main_speaker,name,title,views,ted_talks
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,Do schools kill creativity?,47227110,amazing
1,265,With the same humor and humanity he exuded in ...,977,TED2006,43,Al Gore,Al Gore: Averting the climate crisis,Averting the climate crisis,3200520,pretty good
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,26,David Pogue,David Pogue: Simplicity sells,Simplicity sells,1636292,okay
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,35,Majora Carter,Majora Carter: Greening the ghetto,Greening the ghetto,1697550,okay
4,593,You've never seen data presented like this. Wi...,1190,TED2006,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,The best stats you've ever seen,12005869,amazing
...,...,...,...,...,...,...,...,...,...,...
2545,17,"Between 2008 and 2016, the United States depor...",476,TED2017,4,Duarte Geraldino,Duarte Geraldino: What we're missing in the de...,What we're missing in the debate about immigra...,450430,sucks less
2546,6,How can you study Mars without a spaceship? He...,290,TED2017,3,Armando Azua-Bustos,Armando Azua-Bustos: The most Martian place on...,The most Martian place on Earth,417470,sucks less
2547,10,Science fiction visions of the future show us ...,651,TED2017,1,Radhika Nagpal,Radhika Nagpal: What intelligent machines can ...,What intelligent machines can learn from a sch...,375647,Kinda sucks
2548,32,In an unmissable talk about race and politics ...,1100,TEDxMileHigh,1,Theo E.J. Wilson,Theo E.J. Wilson: A black man goes undercover ...,A black man goes undercover in the alt-right,419309,sucks less
2549,8,With more than half of the world population li...,519,TED2017,1,Karoliina Korppoo,Karoliina Korppoo: How a video game might help...,How a video game might help us build better ci...,391721,Kinda sucks

In [37]:
# Create a GroupBy object based upon "View Group"

viewgroup_df = df.groupby("ted_talks")

# Find how many rows fall into each bin



# Get the average of each column within the GroupBy object